// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UploadedFile struct {
	ID        int32
	UserID    int32
	FileUrl   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}

type UserFcmToken struct {
	ID        int32
	UserID    int32
	FcmToken  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
