// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upload_file.sql

package database

import (
	"context"
)

const createUploadedFile = `-- name: CreateUploadedFile :exec

INSERT INTO uploaded_files (user_id, file_url, created_at, updated_at)
VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateUploadedFileParams struct {
	UserID  int32
	FileUrl string
}

// database/queries/upload_file.sql
// params: CreateUploadedFileParams
func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) error {
	_, err := q.db.Exec(ctx, createUploadedFile, arg.UserID, arg.FileUrl)
	return err
}
