// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec

INSERT INTO users (name, email, password, created_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
RETURNING id, name, email, password, created_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
}

// database/queries/user.sql
// Create user
// params: CreateUserParams
// returns: User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Name, arg.Email, arg.Password)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, created_at
FROM users
WHERE email = $1
`

// Get user by email
// params: GetUserByEmailParams
// returns: User
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
